/**
 * src/commands/init.ts
 *
 * The interactive "agentic-nexus init" command.
 * Guides the user through environment checks, provider config,
 * agent selection, and project file generation.
 */

import * as p from '@clack/prompts';
import pc from 'picocolors';
import { z } from 'zod';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { runAllChecks, type CheckResult } from '../utils/checker.js';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/** Resolve a path relative to the project templates directory */
function templatePath(file: string): string {
  return path.resolve(__dirname, '../../templates', file);
}

/** Resolve a path relative to the user's current working directory */
function cwdPath(file: string): string {
  return path.resolve(process.cwd(), file);
}

function formatCheckResult(result: CheckResult): string {
  const icon = result.ok ? pc.green('✔') : pc.yellow('⚠');
  const label = pc.bold(result.label.padEnd(20));
  const message = result.ok
    ? pc.dim(result.message)
    : pc.yellow(result.message);
  return `  ${icon}  ${label} ${message}`;
}

// ---------------------------------------------------------------------------
// Validators
// ---------------------------------------------------------------------------

const ApiKeySchema = z
  .string()
  .min(10, 'API key must be at least 10 characters.')
  .regex(/^\S+$/, 'API key must not contain spaces.');

// ---------------------------------------------------------------------------
// Agent definitions
// ---------------------------------------------------------------------------

interface AgentDef {
  value: string;
  label: string;
  hint: string;
}

const AVAILABLE_AGENTS: AgentDef[] = [
  {
    value: 'paperclip',
    label: '📎  Paperclip',
    hint: 'The Orchestrator — plans and delegates tasks to worker agents',
  },
  {
    value: 'openclaw',
    label: '🦞  OpenClaw',
    hint: 'The Worker — executes tasks assigned by the Orchestrator',
  },
];

// ---------------------------------------------------------------------------
// LLM Provider definitions
// ---------------------------------------------------------------------------

const LLM_PROVIDERS = [
  { value: 'openrouter', label: '🔀  OpenRouter', hint: 'Default — routes to many providers' },
  { value: 'openai', label: '🤖  OpenAI', hint: 'GPT-4o and family' },
  { value: 'anthropic', label: '🧠  Anthropic', hint: 'Claude Sonnet / Haiku' },
  { value: 'ollama', label: '🦙  Ollama', hint: 'Local models via Ollama' },
] as const;

// ---------------------------------------------------------------------------
// File generation
// ---------------------------------------------------------------------------

/**
 * Generates the .env file in cwd from the user's choices.
 */
function generateEnvFile(params: {
  provider: string;
  apiKey: string;
  agents: string[];
}): void {
  const lines = [
    '# Generated by Agentic-Nexus init',
    `# Provider: ${params.provider}`,
    '',
    `LLM_PROVIDER=${params.provider}`,
    `LLM_API_KEY=${params.apiKey}`,
    '',
    `ENABLED_AGENTS=${params.agents.join(',')}`,
    '',
    '# Network',
    'NEXUS_NETWORK=agentic_nexus_bridge',
  ];
  fs.writeFileSync(cwdPath('.env'), lines.join('\n') + '\n', 'utf-8');
}

/**
 * Copies the docker-compose template into cwd, substituting basic variables.
 */
function generateDockerCompose(params: { agents: string[] }): void {
  const src = templatePath('docker-compose.yml');
  const dest = cwdPath('docker-compose.yml');

  if (!fs.existsSync(src)) {
    throw new Error(`Template not found: ${src}`);
  }

  let content = fs.readFileSync(src, 'utf-8');

  // Inject active services comment
  const agentList = params.agents.join(', ');
  content = content.replace(
    '# ACTIVE_AGENTS_PLACEHOLDER',
    `# Active agents: ${agentList}`
  );

  fs.writeFileSync(dest, content, 'utf-8');
}

// ---------------------------------------------------------------------------
// Main init flow
// ---------------------------------------------------------------------------

export async function runInit(): Promise<void> {
  console.log('');
  p.intro(
    pc.bgCyan(pc.black(' Agentic-Nexus ')) +
      pc.dim('  —  AI Agent Orchestrator Setup')
  );

  // ── Step 1: System Checks ──────────────────────────────────────────────

  const checkSpinner = p.spinner();
  checkSpinner.start('Running environment checks…');

  const results = await runAllChecks();
  const allPassed = results.every((r) => r.ok);

  checkSpinner.stop(
    allPassed
      ? pc.green('Environment checks complete')
      : pc.yellow('Environment checks complete (with warnings)')
  );

  // Print each result
  for (const result of results) {
    console.log(formatCheckResult(result));
    if (!result.ok && result.hint) {
      console.log(pc.dim(`       ↳ ${result.hint.replace(/\n/g, '\n         ')}`));
    }
  }
  console.log('');

  // If Docker is not available, warn but allow the user to continue
  const dockerResult = results.find((r) => r.label === 'Docker / OrbStack');
  if (dockerResult && !dockerResult.ok) {
    p.note(
      'Docker / OrbStack is required to run agents as containers.\n' +
        pc.dim('You can still generate config files and install Docker later.'),
      pc.yellow('⚠  Warning')
    );
  }

  // ── Step 2: Provider Selection ─────────────────────────────────────────

  const provider = await p.select<string>({
    message: 'Which LLM provider would you like to use?',
    options: LLM_PROVIDERS.map((p) => ({
      value: p.value,
      label: p.label,
      hint: p.hint,
    })),
    initialValue: 'openrouter',
  });

  if (p.isCancel(provider)) {
    p.cancel('Setup cancelled.');
    process.exit(0);
  }

  // ── Step 3: API Key ─────────────────────────────────────────────────────

  const apiKey = await p.password({
    message: `Enter your ${pc.bold(String(provider).toUpperCase())} API key:`,
    validate(value) {
      const result = ApiKeySchema.safeParse(value);
      if (!result.success) {
        return result.error.errors[0].message;
      }
    },
  });

  if (p.isCancel(apiKey)) {
    p.cancel('Setup cancelled.');
    process.exit(0);
  }

  // ── Step 4: Agent Selection ─────────────────────────────────────────────

  const selectedAgents = await p.multiselect<string>({
    message: 'Which agents would you like to enable?',
    options: AVAILABLE_AGENTS.map((a) => ({
      value: a.value,
      label: a.label,
      hint: a.hint,
    })),
    initialValues: ['paperclip', 'openclaw'],
    required: true,
  });

  if (p.isCancel(selectedAgents)) {
    p.cancel('Setup cancelled.');
    process.exit(0);
  }

  // ── Step 5: File Generation ─────────────────────────────────────────────

  const genSpinner = p.spinner();
  genSpinner.start('Generating project files…');

  try {
    generateEnvFile({
      provider: String(provider),
      apiKey: String(apiKey),
      agents: selectedAgents as string[],
    });

    generateDockerCompose({ agents: selectedAgents as string[] });

    genSpinner.stop(pc.green('Project files generated successfully!'));
  } catch (err) {
    genSpinner.stop(pc.red('File generation failed.'));
    p.log.error(String(err));
    process.exit(1);
  }

  // ── Summary ─────────────────────────────────────────────────────────────

  p.note(
    [
      `${pc.green('✔')}  ${pc.bold('.env')}               — API key & provider config`,
      `${pc.green('✔')}  ${pc.bold('docker-compose.yml')} — Agent container definitions`,
      '',
      pc.dim('Next steps:'),
      `  ${pc.cyan('docker compose up -d')}   — Start your agents`,
      `  ${pc.cyan('docker compose logs -f')}  — Stream agent logs`,
    ].join('\n'),
    'Setup Complete 🎉'
  );

  p.outro(
    `Powered by ${pc.cyan('Agentic-Nexus')} — ${pc.dim('https://github.com/akkappsoft/agentic-nexus')}`
  );
}
