#!/usr/bin/env bash
# ==============================================================================
# generate.sh — Generate all runtime files from config.json
# ==============================================================================
# Reads config.json and produces:
#   .env.generated               — env vars for docker compose (chmod 600)
#   docker-compose.override.yml  — per-agent services
#
# Run automatically by: make up
# Run manually:          make generate
# ==============================================================================
set -e

cd "$(dirname "$0")/.."

CONFIG="./config.json"
ENV_OUT="./.env.generated"
COMPOSE_OUT="./docker-compose.override.yml"

if [ ! -f "$CONFIG" ]; then
    echo "❌ config.json not found — run: cp config.json.example config.json"
    exit 1
fi

TEAM_NAME=$(jq -r '.team' "$CONFIG")
AGENT_COUNT=$(jq '.agents | length' "$CONFIG")
AGENT_IDS=$(jq -r '.agents[].id' "$CONFIG" | tr '\n' ' ')

echo "🔧 Generating from config.json ..."
echo "   Team: ${TEAM_NAME}  |  Agents (${AGENT_COUNT}): ${AGENT_IDS}"

# ==============================================================================
# 1. .env.generated — all env vars for docker compose
# ==============================================================================
{
    echo "# AUTO-GENERATED by scripts/generate.sh — DO NOT EDIT"
    echo "# Source: config.json  |  Regenerate: make generate"
    echo ""
    echo "TEAM_NAME=$(jq -r '.team' "$CONFIG")"
    echo ""
    echo "HOST_OPENCLAW_DIR=$(jq -r '.disks.openclaw' "$CONFIG")"
    echo "HOST_KM_DIR=$(jq -r '.disks.km' "$CONFIG")"
    echo "HOST_OLLAMA_DIR=$(jq -r '.disks.ollama' "$CONFIG")"
    echo "HOST_CRAWL4AI_DIR=$(jq -r '.disks.crawl4ai' "$CONFIG")"
    echo "HOST_SSL_DIR=$(jq -r '.disks.ssl' "$CONFIG")"
    echo "HOST_MCPORTER_DIR=$(jq -r '.disks.mcporter // "~/Projects/sempre/disks/mcporter"' "$CONFIG")"
    echo ""
    echo "TAILSCALE_HOSTNAME=$(jq -r '.tailscale_hostname' "$CONFIG")"
    echo "NGINX_OPENCLAW_PORT=$(jq -r '.nginx.openclaw_port' "$CONFIG")"
    echo "NGINX_OLLAMA_PORT=$(jq -r '.nginx.ollama_port' "$CONFIG")"
    echo "NGINX_N8N_PORT=$(jq -r '.nginx.n8n_port' "$CONFIG")"
    echo "NGINX_HTTP_PORT=$(jq -r '.nginx.http_port' "$CONFIG")"
    echo ""
    echo "OPENCLAW_GATEWAY_TOKEN=$(jq -r '.openclaw.gateway_token' "$CONFIG")"
    echo "OPENCLAW_ROOT_PASSWORD=$(jq -r '.openclaw.root_password' "$CONFIG")"
    echo "GATEWAY_ORIGIN=$(jq -r '.openclaw.gateway_origin' "$CONFIG")"
    echo "GATEWAY_ORIGIN_EXTRA=https://$(jq -r '.tailscale_hostname' "$CONFIG"):$(jq -r '.nginx.openclaw_port' "$CONFIG")"
    echo ""
    echo "USER_TIMEZONE=$(jq -r '.timezone' "$CONFIG")"
    echo "KM_MAX_HOPS=$(jq -r '.km_max_hops' "$CONFIG")"
    echo ""
    echo "OLLAMA_MODEL=$(jq -r '.llm.model' "$CONFIG")"
    echo "OLLAMA_MODELS=$(jq -r '.llm.models' "$CONFIG")"
    echo "BROWSER_USE_MODEL=$(jq -r '.llm.browser_model' "$CONFIG")"
    echo ""
    echo "BRAVE_API_KEY=$(jq -r '.brave_api_key' "$CONFIG")"
    echo ""
    echo "N8N_ENCRYPTION_KEY=$(jq -r '.n8n.encryption_key' "$CONFIG")"
    echo "N8N_PASSWORD=$(jq -r '.n8n.password' "$CONFIG")"
    echo "N8N_WEBHOOK_SECRET=$(jq -r '.n8n.webhook_secret' "$CONFIG")"
    echo "N8N_API_KEY=$(jq -r '.n8n.api_key' "$CONFIG")"
    echo ""
    echo "GOOGLE_SERVICE_ACCOUNT_B64=$(jq -r '.google_service_account_b64' "$CONFIG")"
    echo ""
    while IFS= read -r agent; do
        id=$(echo "$agent" | jq -r '.id')
        discord=$(echo "$agent" | jq -r '.discord_token // ""')
        github=$(echo "$agent"  | jq -r '.github_token  // ""')
        echo "DISCORD_BOT_TOKEN_${id}=${discord}"
        echo "GITHUB_TOKEN_${id}=${github}"
    done < <(jq -c '.agents[]' "$CONFIG")
} > "$ENV_OUT"

chmod 600 "$ENV_OUT"

# ==============================================================================
# 2. docker-compose.override.yml — per-agent services
# ==============================================================================
{
    echo "# AUTO-GENERATED by scripts/generate.sh — DO NOT EDIT MANUALLY"
    echo "# Source: config.json  |  Regenerate: make generate"
    echo ""
    echo "services:"
    echo ""

    echo "  openclaw:"
    echo "    env_file:"
    echo "      - .env.generated"
    echo "    volumes:"
    echo "      - ./config.json:/opt/sempre/config.json:ro"
    echo "    depends_on:"
    while IFS= read -r agent; do
        id=$(echo "$agent" | jq -r '.id')
        echo "      gh-proxy-${id}:"
        echo "        condition: service_started"
        echo "      crawl4ai-${id}:"
        echo "        condition: service_started"
        echo "      browser-use-${id}:"
        echo "        condition: service_started"
    done < <(jq -c '.agents[]' "$CONFIG")
    echo ""

    while IFS= read -r agent; do
        id=$(echo "$agent" | jq -r '.id')

        echo "  gh-proxy-${id}:"
        echo "    build:"
        echo "      context: ./docker/gh-proxy"
        echo "      dockerfile: Dockerfile"
        echo "    container_name: gh-proxy-${id}"
        echo "    environment:"
        echo "      - GITHUB_TOKEN=\${GITHUB_TOKEN_${id}:-}"
        echo "    restart: unless-stopped"
        echo "    networks:"
        echo "      default:"
        echo "        aliases:"
        echo "          - gh-proxy-${id}"
        echo ""

        echo "  crawl4ai-${id}:"
        echo "    image: unclecode/crawl4ai:latest"
        echo "    container_name: crawl4ai-${id}"
        echo "    shm_size: \"2gb\""
        echo "    volumes:"
        echo "      - \${HOST_CRAWL4AI_DIR:-~/.sempre/crawl4ai}/${id}:/app/data"
        echo "    restart: unless-stopped"
        echo "    networks:"
        echo "      default:"
        echo "        aliases:"
        echo "          - crawl4ai-${id}"
        echo ""

        echo "  browser-use-${id}:"
        echo "    build:"
        echo "      context: ./docker/browser-use"
        echo "      dockerfile: Dockerfile"
        echo "    container_name: browser-use-${id}"
        echo "    environment:"
        echo "      - OLLAMA_BASE_URL=http://ollama:11434/v1"
        echo "      - OLLAMA_MODEL=\${BROWSER_USE_MODEL:-minimax-m2.5:cloud}"
        echo "    shm_size: \"2gb\""
        echo "    restart: unless-stopped"
        echo "    networks:"
        echo "      default:"
        echo "        aliases:"
        echo "          - browser-use-${id}"
        echo ""

    done < <(jq -c '.agents[]' "$CONFIG")

} > "$COMPOSE_OUT"

echo "✅ Generated: .env.generated (600) · docker-compose.override.yml"
echo "   ${AGENT_COUNT} agents · $(( AGENT_COUNT * 3 )) per-agent services"

# ==============================================================================
# 3. Ensure host disk directories exist
# ==============================================================================
while IFS='=' read -r key val; do
    [[ "$key" == HOST_*_DIR ]] || continue
    dir="${val/\~/$HOME}"
    mkdir -p "$dir"
done < "$ENV_OUT"
echo "📁 Disk directories ensured"
