networks:
  agentic_nexus_bridge:
    name: agentic_nexus_bridge
    driver: bridge

services:
  # ============================================================================
  # Ollama – LLM backend (routes cloud models to Minimax/etc.)
  # ============================================================================
  ollama:
    build:
      context: ./docker/ollama
      dockerfile: Dockerfile
    container_name: ollama
    environment:
      - OLLAMA_NUM_CTX=16384
      - OLLAMA_KEEP_ALIVE=1h
      - OLLAMA_NUM_PARALLEL=3
      - OLLAMA_MODELS=${OLLAMA_MODELS:-minimax-m2.5:cloud}
      - GOMAXPROCS=1
    ports:
      - "11434:11434"
    volumes:
      - ./data/ollama:/root/.ollama
    restart: unless-stopped
    networks:
      - agentic_nexus_bridge
  # ============================================================================
  # OpenClaw Gateway (Ubuntu + SSH)
  # ============================================================================
  openclaw:
    build:
      context: ./docker/openclaw-test
      dockerfile: Dockerfile
    container_name: openclaw
    env_file:
      - .env
    environment:
      - HOME=/root
      - TERM=xterm-256color
      - TEAM_NAME=${TEAM_NAME:-nexus}
      - OPENCLAW_GATEWAY_TOKEN=${OPENCLAW_GATEWAY_TOKEN}
      - OPENCLAW_ROOT_PASSWORD=${OPENCLAW_ROOT_PASSWORD:-openclaw}
      - OPENCLAW_GATEWAY_BIND=${OPENCLAW_GATEWAY_BIND:-lan}
      - GATEWAY_ORIGIN=${GATEWAY_ORIGIN:-http://localhost:18789}
      - GATEWAY_ORIGIN_EXTRA=${GATEWAY_ORIGIN_EXTRA:-}
      # LLM
      - OLLAMA_MODEL=${OLLAMA_MODEL:-minimax-m2.5:cloud}
      - OLLAMA_MODELS=${OLLAMA_MODELS:-minimax-m2.5:cloud}
      # KM
      - KM_MAX_HOPS=${KM_MAX_HOPS:-2}
      # Timezone
      - USER_TIMEZONE=${USER_TIMEZONE:-Asia/Bangkok}
      # Per-agent secrets (DISCORD_BOT_TOKEN_{id}, GITHUB_TOKEN_{id}) come from
      # env_file in docker-compose.override.yml (generated by scripts/generate.sh)
      # Brave Search
      - BRAVE_API_KEY=${BRAVE_API_KEY:-}
      # n8n
      - N8N_API_KEY=${N8N_API_KEY:-}
      - N8N_WEBHOOK_SECRET=${N8N_WEBHOOK_SECRET:-}
      # Google Workspace
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS:-/root/.gws/service-account.json}
      - GOOGLE_SERVICE_ACCOUNT_B64=${GOOGLE_SERVICE_ACCOUNT_B64:-}
    volumes:
      - ${HOST_OPENCLAW_DIR:-~/.nexus/openclaw}:/root/.openclaw
      - ${HOST_KM_DIR:-~/.nexus/km}:/root/.km
      - ${HOST_MCPORTER_DIR:-~/.nexus/mcporter}:/root/.mcporter
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "2222:22" # SSH only — web UI is served via nginx SSL
    shm_size: "2gb"
    restart: unless-stopped
    networks:
      default:
        aliases:
          - agentic_nexus_bridge
    healthcheck:
      test: [ "CMD-SHELL", "curl -sf http://$(hostname -I | awk '{print $1}'):18789/healthz" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      - ollama
